const products = [
    { "id": "1", "title": "Awesome Concrete Shoes", "price": "25.1", "category": "Widget" },
    { "id": "2", "title": "Aerodynamic Paper Computer", "price": "25.1", "category": "Widget" },
    { "id": "3", "title": "Intelligent Wooden Gloves", "price": "24.88", "category": "Gizmo" },
    { "id": "4", "title": "Enormous Marble Shoes", "price": "21.42", "category": "Gizmo" },
    { "id": "5", "title": "Awesome Rubber Wallet", "price": "25.34", "category": "Widget" },
    { "id": "6", "title": "Awesome Silk Car", "price": "24.25", "category": "Doohickey" },
    { "id": "7", "title": "Rustic Paper Car", "price": "19.87", "category": "Doohickey" },
    { "id": "8", "title": "Mediocre Paper Car", "price": "15.69", "category": "Gizmo" },
    { "id": "9", "title": "Aerodynamic Granite Bottle", "price": "27.5", "category": "Gizmo" },
    { "id": "10", "title": "Mediocre Aluminum Shirt", "price": "27.74", "category": "Gizmo" },
    { "id": "11", "title": "Sleek Aluminum Clock", "price": "27.74", "category": "Gizmo" },
    { "id": "12", "title": "Small Wool Wallet", "price": "27.55", "category": "Doohickey" },
    { "id": "13", "title": "Ergonomic Wool Bag", "price": "26.96", "category": "Doohickey" },
    { "id": "14", "title": "Heavy-Duty Copper Gloves", "price": "20.41", "category": "Gadget" },
    { "id": "15", "title": "Aerodynamic Cotton Lamp", "price": "23.69", "category": "Widget" },
    { "id": "16", "title": "Gorgeous Copper Knife", "price": "22.38", "category": "Gadget" },
    { "id": "17", "title": "Ergonomic Leather Pants", "price": "22.38", "category": "Widget" },
    { "id": "18", "title": "Aerodynamic Copper Knife", "price": "25.54", "category": "Gizmo" },
    { "id": "19", "title": "Rustic Copper Hat", "price": "25.54", "category": "Doohickey" },
    { "id": "20", "title": "Sleek Marble Table", "price": "26.38", "category": "Gadget" },
    { "id": "21", "title": "Synergistic Copper Computer", "price": "22.58", "category": "Doohickey" }
]